Repository RGB-WG/rgb-std, pull requests merged in 2024-06, with the labels that each got.

#204 Coin amount type
  invoice/src/amount.rs
  invoice/src/builder.rs
  invoice/src/lib.rs
Labels: enhancement

#203 Support custom close methods in vout-based invoices
  Cargo.lock
  Cargo.toml
  invoice/src/builder.rs
  invoice/src/invoice.rs
  invoice/src/lib.rs
  invoice/src/parse.rs
  src/persistence/stock.rs
Labels: bug, enhancement

#206 more-interface-features
  src/interface/builder.rs
  src/interface/iimpl.rs
  src/persistence/stock.rs
Labels: enhancement

#209 Require invoice URIs not to contain authority
  invoice/src/parse.rs
Labels: bug

#214 fix: invoice baid64 encode & decode for P2TR address
  invoice/src/invoice.rs
  invoice/src/parse.rs
Labels: bug

#210 fix bug: Pay2Vout's to_baid64_payload and try_from
  invoice/src/parse.rs
Labels: bug

#217 check ifaceid, bundleid in consignment
  src/containers/consignment.rs
Labels: enhancement

#218 drop tick and backtick from amount group separator list
  invoice/src/amount.rs
Labels: enhancement

#219 add rights, attachment operations
  src/interface/contract.rs
Labels: enhancement

#224 fix now -> not typo
  src/persistence/stock.rs
Labels: bug, documentation

#229 check add and sub operation for owned fraction
  invoice/src/data.rs
Labels: enhancement

#228 unreachable to ord for amount
  src/interface/contract.rs
Labels: enhancement

#230 Collect supplyment features in consign
  src/persistence/memory.rs
  src/persistence/stash.rs
  src/persistence/stock.rs
Labels: enhancement
